name = "cp"
main = ".open-next/worker.js"
compatibility_date = "2026-06-20"
compatibility_flags = ["nodejs_compat"]

assets = { directory = ".open-next/assets", binding = "ASSETS" }

# ===== D1 Database =====
[[d1_databases]]
binding = "DB"
database_name = "cp-db"
database_id = "0a290c4a-cfa3-46ca-bc66-88bfc241e91f"
